### ISSUE TITLE
dependency to gdx-pay-client:0.6.0-SNAPSHOT

### ISSUE THREAD

**Issue by arashbi** [libgdx/gdx-pay#71] opened 2015-11-22 00:32 UTC
The released version of android pay has a dependency to the above mentioned jar, which doesn't exist in the maven repo. I think you need to update to to the released version

**Comment by xoppa** [comment] 2015-11-22 00:39
Duplicate of #67, PR welcome.

**Closed** 2015-11-23 03:20 UTC
