### ISSUE TITLE
IOS developer will need to implement “paymentQueue:shouldAddStorePayment:forProduct:” in order for the IAP product to be promoted

### ISSUE THREAD

**Issue by Glyfad** [libgdx/gdx-pay#175] opened 2018-08-04 13:31 UTC
Hi, 
Apple App store support engineers require the method  'paymentQueue:shouldAddStorePayment' need to be implemented in order to application can be promoted in App Store. 

Could you please take this into consideration in the next commit.

Thanks in advance

**Comment by keesvandieren** [comment] 2018-08-04 14:33
I have added the method to the gdx-pay Robovm client, and published updated SNAPSHOT versions (0.11.3-SNAPSHOT) to https://oss.sonatype.org/content/repositories/snapshots/

If it works well there, it also has to be added to iosmoe variant. 

Can you try them and see if they work as intended?

Thanks so much for testing. Looking forward to your reaction.

**Comment by Glyfad** [comment] 2018-08-04 16:52
I have no experience to work with snapshots, I would be very appreciate if you kindly assist me in further steps, or at least provide me with references to read. I use Android Studio being installed on Mac. 

appreciate

**Comment by keesvandieren** [comment] 2018-08-04 17:46
Step 1: add the SNAPSHOT repository into root build.gradle. See https://github.com/libgdx/gdx-pay/blob/master/build.gradle#L90 for an example. Shortest example:

    allprojects {
        repositories {
            maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
       }
   }

Set version to 0.11.3-SNAPSHOT (instead of current 0.11.2)

Than, re-import project into Android Studio. Is this enough?

**Comment by Glyfad** [comment] 2018-08-04 21:48
Yes this is enough. The IPA has been created without problems. 
But new problems arise with uploading through iTune. When I resolve them {  if :(   } then I let you know.

PS
I did not touch my mac for a month since my last uploading, i did not change nothing and got surprises with invalid signature & SDK. version. I also tried to upload my previous IPA (that already published in the market) and got the same errors. Well....

**Comment by keesvandieren** [comment] 2018-08-06 08:46
What is the problem you have? It won't upload?

Maybe you can read https://www.squins.com/knowledge/robovm-launching-and-signing-issues/; does that help?

Are you creating IPA using Gradle or using IDEA / Android Studio? When using gradle, I always execute a `gradlew clean` before creating the IPA.

**Comment by Glyfad** [comment] 2018-08-06 09:16
Yes it won't.

1 package(s) were not uploaded because they had problems:
	/var/folders/sd/0b1f0vfn1fs_r4g62knvl3mm0000gn/T/7A56A98D-CE23-4995-AE80-EE8DC8DDDD94/1393771622.itmsp - Error Messages:
		ERROR ITMS-90035: "Invalid Signature. A sealed resource is missing or invalid. The file at path [IOSLauncher.app/IOSLauncher] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"
		ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS '${appSDKVersion}' SDK. All iOS apps submitted to the App Store must be built with the iOS '11.0' SDK or later, included in Xcode [9.0] or later. Please update Xcode and rebuild your app."

I use 'Create IPA' option in Android studio. The key thing I do not understand is why i got the same errors when I try (for testing purpose) to upload old binary which I have already uploaded before and this old binary has been already approved and published in the Apple market. 

I'll try recommendations in the article you provide me.

**Comment by keesvandieren** [comment] 2018-08-06 11:02
I have had this issue too. Upgrade to robovm 2.3.4, see robovm gitter chatlog on 1 June for background info: https://gitter.im/MobiVM/robovm?at=5b1151c4f9f2e56cf2319d96

**Comment by keesvandieren** [comment] 2018-11-24 22:18
@Glyfad can you update me on this?

**Comment by MrStahlfelge** [comment] 2019-03-16 19:41
I'll close this now. It's not sure if it works as intended, but apparently there's no problem for a user at the moment.

**Closed by MrStahlfelge** 2019-03-16 19:41 UTC
Labels: apple, ios-robovm

**Comment by gagbaghdas** [comment] 2019-04-11 06:35
Hi guys. 

I have this issue now. 

Did you able to fix it after gdx-pay update  to 0.11.3-SNAPHOT?

I'm using 0.12.1-SNAPSHOT. 

Thanks.
