### ISSUE TITLE
gdx-pay-android-googleplay with already purchased item

### ISSUE THREAD

**Issue by Trurl101** [libgdx/gdx-pay#99] opened 2016-02-28 18:18 UTC
If I try to purchase an already purchased item it runs correct for the first time. Google Play overlay opens and tells the user that he already owns it.

But on the second time gdx-pay-android-googleplay returns an exception: "com.badlogic.gdx.pay.android.googleplay.d: startPurchaseRequest failed at getBuyIntent() for product"

**Comment by mustii82** [comment] 2016-04-10 02:53
Yes thats right because you doesn't CONSUME it if you buy an consumable Product you must consume it by yourself. But if you read the Documentary this Library doesent support consumable Items at this time :/

**Comment by deepakraod** [comment] 2016-05-18 06:15
Any update on this ?

**Comment by mustii82** [comment] 2016-05-20 11:08
No 😔

**Comment by Gintasz** [comment] 2016-05-22 17:39
Why are they not supported? What is wrong with consumable items?

**Comment by mustii82** [comment] 2016-05-22 18:49
The library doesn't support it it haven't even a working sample project yet many things are outdated we must update the documentary and publish a working sample otherwise people can't working on new features efficiently

**Comment by noblemaster** [comment] 2016-05-25 07:55
Duplicate of #101.

**Closed by noblemaster** 2016-05-25 07:55 UTC
